-- MySQL Script generated by MySQL Workbench
-- 05/03/16 13:56:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rt` ;

-- -----------------------------------------------------
-- Schema rt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rt` DEFAULT CHARACTER SET utf8 ;
USE `rt` ;

-- -----------------------------------------------------
-- Table `rt`.`kmn_sl_nach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rt`.`kmn_sl_nach` ;

CREATE TABLE IF NOT EXISTS `rt`.`kmn_sl_nach` (
  `PERIOD` DATE NOT NULL,
  `FILIAL` VARCHAR(64) NOT NULL,
  `LOGIN` VARCHAR(32) NOT NULL,
  `FIO` VARCHAR(128) NULL,
  `ACTIVATED_SUBS` DECIMAL(10) NULL DEFAULT 0,
  `TARIFF` DECIMAL(15,2) NULL,
  `INV_CHARGES` DECIMAL(15,2) NULL,
  PRIMARY KEY (`PERIOD`, `FILIAL`, `LOGIN`))
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO root;
 DROP USER root;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'root' IDENTIFIED BY 'root';

GRANT ALL ON `rt`.* TO 'root';
SET SQL_MODE = '';
GRANT USAGE ON *.* TO info_tablo;
 DROP USER info_tablo;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'info_tablo' IDENTIFIED BY 'info_tablo';

GRANT SELECT ON TABLE `rt`.* TO 'info_tablo';
GRANT SELECT ON TABLE `rt`.`kmn_sl_nach` TO 'info_tablo';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
